class AppRoutes {
  AppRoutes._();

  static const String splash = '/splash';
  static const String lngSelect = '/lngSelect';
  static const String onboarding1 = '/onboarding1';
  static const String onboarding2 = '/onboarding2';
  static const String onboarding3 = '/onboarding3';
  static const String accountSelection = '/accountSelection';
  static const String login = '/login';
  static const String mainRegister = '/mainRegister';
  static const String followUpRegisterPatient = '/followUpRegisterPatient';
  static const String followUpRegisterDoctor = '/followUpRegisterDoctor';
  static const String uploadMedicalRecords = '/uploadMedicalRecords';
  static const String medicalRecordsHistory = '/medicalRecordsHistory';
  static const String healthIssues = '/healthIssues';
  static const String addHealthIssue = '/addHealthIssue';
  static const String familyMember = '/familyMember';
  static const String addFamilyMember = '/addFamilyMember';
  static const String notifications = '/notifications';
  static const String appointments = '/appointments';
  static const String home = '/home';
  static const String hospitalhome = '/hospitalhome';
  static const String verification = '/verification';
  static const String verifyDoctor = '/verifyDoctor';
  static const String clinicDetails = '/clinicDetails';
  static const String doctorProfileSettings = '/doctorProfileSettings';
  static const String patientProfileSettings = '/patientProfileSettings';
  static const String doctorProfileView = '/doctorProfileView';
  static const String bookingDetails = '/bookingDetails';
  static const String bookingInformation = '/bookingInformation';
  static const String appointmentSummary = '/appointmentSummary';
  static const String bookingSummary = '/bookingSummary';
  static const String bookingConfirmation = '/bookingConfirmation';
  static const String appointmentDetails = '/appointmentDetails';
  static const String doctorChatRoom = '/doctorChatRoom';
  static const String clinicManagement = '/clinicManagement';
  static const String medicalFacilityManagement = '/medicalFacilityManagement';
  static const String search = '/search';
  static const String searchFilter = '/searchFilter';
  static const String wallet = '/wallet';
  static const String nouga = '/chatbot';
  static const String inbox = '/inbox';
  static const String userManagement = '/userManagement';
}
